const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('api', {
    login: (credentials) => ipcRenderer.invoke('login', credentials),
    getInventory: (sucursalId) => ipcRenderer.invoke('get-inventory', sucursalId),
    registrarVenta: (datosVenta) => ipcRenderer.invoke('registrar-venta', datosVenta),
    registrarGasto: (datosGasto) => ipcRenderer.invoke('registrar-gasto', datosGasto),
    getReporteDiario: (filtros) => ipcRenderer.invoke('get-reporte-diario', filtros),
    registrarProducto: (datosProducto) => ipcRenderer.invoke('registrar-producto', datosProducto),
    getPathForFile: (file) => webUtils.getPathForFile(file),
    editarProducto: (datosProducto) => ipcRenderer.invoke('editar-producto', datosProducto),

    eliminarProducto: (datos) => ipcRenderer.invoke('eliminar-producto', datos),
    exportarPDF: () => ipcRenderer.invoke('exportar-pdf'),
    generarCuentaCobroPDF: (clienteId) => ipcRenderer.invoke('generar-cuenta-cobro-pdf', clienteId),
    generarCuentaCobroVentaPDF: (datos) => ipcRenderer.invoke('generar-cuenta-cobro-venta-pdf', datos),
    editarGasto: (datosGasto) => ipcRenderer.invoke('editar-gasto', datosGasto),
    eliminarGasto: (datos) => ipcRenderer.invoke('eliminar-gasto', datos),
    obtenerDescripcionesFrecuentesGasto: (datos) => ipcRenderer.invoke('obtener-descripciones-frecuentes-gasto', datos),
    actualizarEstadoDevolucion: (datos) => ipcRenderer.invoke('actualizar-estado-devolucion', datos),
    obtenerReporteDevoluciones: (filtros) => ipcRenderer.invoke('obtener-reporte-devoluciones', filtros),
    obtenerSucursal: (id) => ipcRenderer.invoke('obtener-sucursal', id),
    guardarSucursal: (datos) => ipcRenderer.invoke('guardar-sucursal', datos),
    obtenerUsuarios: () => ipcRenderer.invoke('obtener-usuarios'),
    guardarUsuario: (datos) => ipcRenderer.invoke('guardar-usuario', datos),
    eliminarUsuario: (id) => ipcRenderer.invoke('eliminar-usuario', id),
    cambiarPasswordPropio: (datos) => ipcRenderer.invoke('cambiar-password-propio', datos),
    editarVenta: (datosVenta) => ipcRenderer.invoke('editar-venta', datosVenta),
    eliminarVenta: (datos) => ipcRenderer.invoke('eliminar-venta', datos),
    obtenerSucursalId: () => ipcRenderer.invoke('obtener-sucursal-id'),
    obtenerSucursalesDisponibles: () => ipcRenderer.invoke('obtener-sucursales-disponibles'),
    abastecerStock: (datos) => ipcRenderer.invoke('abastecer-stock', datos),
    generarPlantillaAbastecimiento: (datos) => ipcRenderer.invoke('generar-plantilla-abastecimiento', datos),
    previsualizarAbastecimientoArchivo: (datos) => ipcRenderer.invoke('previsualizar-abastecimiento-archivo', datos),
    confirmarAbastecimientoMasivo: (datos) => ipcRenderer.invoke('confirmar-abastecimiento-masivo', datos),
    obtenerTodasSucursales: () => ipcRenderer.invoke('obtener-todas-sucursales'),
    activarSucursal: (id) => ipcRenderer.invoke('activar-sucursal', id),
    eliminarSucursal: (id) => ipcRenderer.invoke('eliminar-sucursal', id),
    obtenerCategorias: () => ipcRenderer.invoke('obtener-categorias'),
    guardarCategoria: (datos) => ipcRenderer.invoke('guardar-categoria', datos),
    eliminarCategoria: (id) => ipcRenderer.invoke('eliminar-categoria', id),
    forceRefocus: () => ipcRenderer.invoke('force-refocus'),
    realizarTransferencia: (datos) => ipcRenderer.invoke('realizar-transferencia', datos),
    eliminarTransferencia: (datos) => ipcRenderer.invoke('eliminar-transferencia', datos),
    obtenerBalanceFinanciero: (filtros) => ipcRenderer.invoke('obtener-balance-financiero', filtros),
    obtenerRankingProductos: (filtros) => ipcRenderer.invoke('obtener-ranking-productos', filtros),
    forzarSincronizacion: () => ipcRenderer.invoke('forzar-sincronizacion'),
    abrirVentanaVentas: () => ipcRenderer.invoke('abrir-ventana-ventas'),
    obtenerAniosDisponibles: () => ipcRenderer.invoke('obtener-anios-disponibles'),
    obtenerMesesDisponibles: (anio) => ipcRenderer.invoke('obtener-meses-disponibles', anio),
    onInventarioActualizado: (callback) => ipcRenderer.on('inventario-actualizado', (event, ...args) => callback(...args)),
    onSincronizacionCompleta: (callback) => ipcRenderer.on('sincronizacion-completa', () => callback()),
    onSincronizacionEstado: (callback) => ipcRenderer.on('sincronizacion-estado', (event, enCurso) => callback(enCurso)),
    isSincronizando: () => ipcRenderer.invoke('is-sincronizando'),

    // Módulo de créditos a clientes
    obtenerClientes: () => ipcRenderer.invoke('obtener-clientes'),
    guardarCliente: (datos) => ipcRenderer.invoke('guardar-cliente', datos),
    eliminarCliente: (id) => ipcRenderer.invoke('eliminar-cliente', id),
    obtenerAbonos: (clienteId) => ipcRenderer.invoke('obtener-abonos', clienteId),
    registrarAbono: (datos) => ipcRenderer.invoke('registrar-abono', datos),
    eliminarAbono: (id) => ipcRenderer.invoke('eliminar-abono', id),
    obtenerReporteCreditos: (params) => ipcRenderer.invoke('obtener-reporte-creditos', params),

    // Módulo de Ventas de Fecha Anterior (con cola de aprobación para Operadores)
    registrarVentaAnterior: (datos) => ipcRenderer.invoke('registrar-venta-anterior', datos),
    obtenerDetalleVenta: (ventaId) => ipcRenderer.invoke('obtener-detalle-venta', ventaId),
    editarVentaAnterior: (datos) => ipcRenderer.invoke('editar-venta-anterior', datos),
    eliminarVentaAnterior: (datos) => ipcRenderer.invoke('eliminar-venta-anterior', datos),
    obtenerSolicitudesVenta: (filtros) => ipcRenderer.invoke('obtener-solicitudes-venta', filtros),
    aprobarSolicitudVenta: (datos) => ipcRenderer.invoke('aprobar-solicitud-venta', datos),
    rechazarSolicitudVenta: (datos) => ipcRenderer.invoke('rechazar-solicitud-venta', datos),
    contarSolicitudesPendientes: () => ipcRenderer.invoke('contar-solicitudes-pendientes'),

    // Módulo de Logs de Auditoría (Administrador)
    obtenerAuditoria: (filtros) => ipcRenderer.invoke('obtener-auditoria', filtros),
    obtenerAccionesAuditoria: () => ipcRenderer.invoke('obtener-acciones-auditoria'),
    obtenerUsuariosAuditoria: () => ipcRenderer.invoke('obtener-usuarios-auditoria'),

    // Módulo de impresión térmica
    listarImpresoras: () => ipcRenderer.invoke('listar-impresoras'),
    obtenerImpresoraGuardada: () => ipcRenderer.invoke('obtener-impresora-guardada'),
    guardarImpresoraLocal: (nombre) => ipcRenderer.invoke('guardar-impresora-local', nombre),
    imprimirTicket: (datosTicket, printerName) => ipcRenderer.invoke('imprimir-ticket', { printerName, datosTicket }),
    imprimirTicketPedido: (datosTicket, printerName) => ipcRenderer.invoke('imprimir-ticket-pedido', { printerName, datosTicket }),
    onImpresionFallida: (callback) => ipcRenderer.on('impresion-fallida', (event, mensaje) => callback(mensaje)),

    // Módulo de Pedidos/Apartados
    crearPedido: (datos) => ipcRenderer.invoke('crear-pedido', datos),
    obtenerPedidos: (filtros) => ipcRenderer.invoke('obtener-pedidos', filtros),
    obtenerDetallePedido: (pedidoId) => ipcRenderer.invoke('obtener-detalle-pedido', pedidoId),
    editarPedido: (datos) => ipcRenderer.invoke('editar-pedido', datos),
    registrarAbonoPedido: (datos) => ipcRenderer.invoke('registrar-abono-pedido', datos),
    eliminarAbonoPedido: (datos) => ipcRenderer.invoke('eliminar-abono-pedido', datos),
    entregarPedido: (datos) => ipcRenderer.invoke('entregar-pedido', datos),
    cancelarPedido: (datos) => ipcRenderer.invoke('cancelar-pedido', datos),
    contarPedidosAtrasados: () => ipcRenderer.invoke('contar-pedidos-atrasados'),

    // Módulo de Cierres de Caja (cuadre por ventana de tiempo)
    obtenerVentanaCajaActual: (datos) => ipcRenderer.invoke('obtener-ventana-caja-actual', datos),
    registrarCierreCaja: (datos) => ipcRenderer.invoke('registrar-cierre-caja', datos),
    obtenerCierresCaja: (filtros) => ipcRenderer.invoke('obtener-cierres-caja', filtros),
    eliminarCierreCaja: (datos) => ipcRenderer.invoke('eliminar-cierre-caja', datos)
});
